"use client";

import React, { useState, useCallback, useEffect, useRef } from "react";
import QRCode from "qrcode";
import { ToolLayout } from "@/components/tool/tool-layout";
import { UpgradeGate, ProBadge } from "@/components/billing/upgrade-gate";
import { usePlan } from "@/components/billing/plan-provider";
import { useI18n } from "@/i18n";
import { QrCode, Palette, Image, Download, ZoomIn } from "lucide-react";

const RELATED_SLUGS = ["password-generator", "uuid-generator", "json-formatter"] as const;

const RELATED_ICONS: Record<string, string> = {
  "password-generator": "K",
  "uuid-generator": "U",
  "json-formatter": "{}",
};

const LONG_DESCRIPTION =
  "Create custom QR codes for URLs, text, or any data. Choose from multiple error correction levels, customize foreground and background colors, add a logo in the center, and download as PNG or SVG. Powered by the qrcode library.";

const FAQ = [
  { question: "What is error correction in QR codes?", answer: "Error correction allows QR codes to be read even if partially damaged. L (7%) recovers up to 7% damage, M (15%) for moderate damage, Q (25%) for high damage, and H (30%) for very high damage. Higher levels produce denser QR codes." },
  { question: "Can I scan QR codes generated by this tool?", answer: "Yes! Any standard QR code scanner app can scan QR codes generated by our tool. They are fully compliant with ISO/IEC 18004 standards." },
  { question: "Why use higher error correction?", answer: "Higher error correction is useful when you plan to add a logo overlay, expect the QR code to be printed on curved surfaces, or anticipate partial damage." },
];

const ARTICLE = {
  title: "How QR Codes Work",
  content: "QR (Quick Response) codes are two-dimensional barcodes that can store data like URLs, text, or contact information. They use Reed-Solomon error correction to remain readable even when partially damaged. QR codes have finder patterns in three corners for orientation, timing patterns for module positioning, and data modules encoded with error correction. Our generator uses the industry-standard qrcode library.",
};

const PRESETS = [
  { fg: "#000000", bg: "#ffffff", name: "Classic" },
  { fg: "#0d6efd", bg: "#ffffff", name: "Blue" },
  { fg: "#198754", bg: "#ffffff", name: "Green" },
  { fg: "#dc3545", bg: "#ffffff", name: "Red" },
  { fg: "#6f42c1", bg: "#ffffff", name: "Purple" },
  { fg: "#ffffff", bg: "#000000", name: "Inverted" },
  { fg: "#000000", bg: "#ffd700", name: "Gold" },
  { fg: "#20c997", bg: "#ffffff", name: "Teal" },
];

export default function QRCodeGeneratorPage() {
  const { dict } = useI18n();
  const t = dict.tools;
  const category = t.categories.developer;
  const meta = t.meta["qr-code-generator"];

  const tool = {
    name: meta.name,
    description: meta.description,
    longDescription: LONG_DESCRIPTION,
    category,
    categorySlug: "developer",
    icon: <QrCode className="h-6 w-6" />,
    breadcrumbs: [
      { label: category, href: "/category/developer" },
      { label: meta.name, href: "/tools/qr-code-generator" },
    ],
  };

  const relatedTools = RELATED_SLUGS.map((slug) => ({
    slug,
    name: t.meta[slug].name,
    description: t.meta[slug].short,
    icon: RELATED_ICONS[slug] ?? "+",
  }));

  const presetLabels: Record<string, string> = {
    Classic: t.qrCode.presetClassic,
    Blue: t.qrCode.presetBlue,
    Green: t.qrCode.presetGreen,
    Red: t.qrCode.presetRed,
    Purple: t.qrCode.presetPurple,
    Inverted: t.qrCode.presetInverted,
    Gold: t.qrCode.presetGold,
    Teal: t.qrCode.presetTeal,
  };

  const [text, setText] = useState("https://toolnova.com");
  const [ecLevel, setEcLevel] = useState<"L" | "M" | "Q" | "H">("M");
  const [fg, setFg] = useState("#000000");
  const [bg, setBg] = useState("#ffffff");
  const [size, setSize] = useState(300);
  const [logoDataUrl, setLogoDataUrl] = useState<string | null>(null);
  const [qrDataUrl, setQrDataUrl] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [gate, setGate] = useState<null | "svg">(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const logoCanvasRef = useRef<HTMLCanvasElement>(null);

  const { plan, limitFor } = usePlan();
  const maxSize = limitFor("qrMaxSize") ?? 800;

  useEffect(() => {
    if (size > maxSize) setSize(maxSize);
  }, [size, maxSize]);

  useEffect(() => {
    if (plan !== "free" && gate !== null) setGate(null);
  }, [plan, gate]);

  const generate = useCallback(async () => {
    try {
      setError("");
      if (!text.trim()) { setError(t.qrCode.enterTextOrUrl); return; }
      const url = await QRCode.toDataURL(text, {
        width: size,
        margin: 2,
        color: { dark: fg, light: bg },
        errorCorrectionLevel: ecLevel,
      });
      setQrDataUrl(url);
    } catch (e) {
      setError(e instanceof Error ? e.message : t.qrCode.failedGenerate);
      setQrDataUrl(null);
    }
  }, [text, ecLevel, fg, bg, size, t]);

  useEffect(() => { generate(); }, [generate]);

  const handleLogoUpload = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => setLogoDataUrl(reader.result as string);
    reader.readAsDataURL(file);
  }, []);

  const getFinalCanvas = useCallback(() => {
    if (!qrDataUrl) return null;
    const canvas = document.createElement("canvas");
    const img = new window.Image();
    canvas.width = size;
    canvas.height = size;
    const ctx = canvas.getContext("2d");
    if (!ctx) return null;
    return new Promise<HTMLCanvasElement | null>((resolve) => {
      img.onload = () => {
        ctx.drawImage(img, 0, 0, size, size);
        if (logoDataUrl) {
          const logoSize = size * 0.25;
          const logoX = (size - logoSize) / 2;
          const logoY = (size - logoSize) / 2;
          const logoImg = new window.Image();
          logoImg.onload = () => {
            ctx.fillStyle = bg;
            ctx.beginPath();
            ctx.arc(size / 2, size / 2, logoSize / 2 + 3, 0, Math.PI * 2);
            ctx.fill();
            ctx.save();
            ctx.beginPath();
            ctx.arc(size / 2, size / 2, logoSize / 2, 0, Math.PI * 2);
            ctx.clip();
            ctx.drawImage(logoImg, logoX, logoY, logoSize, logoSize);
            ctx.restore();
            resolve(canvas);
          };
          logoImg.onerror = () => resolve(canvas);
          logoImg.src = logoDataUrl;
        } else {
          resolve(canvas);
        }
      };
      img.onerror = () => resolve(null);
      img.src = qrDataUrl;
    });
  }, [qrDataUrl, logoDataUrl, size, bg]);

  const downloadPNG = useCallback(async () => {
    const canvas = await getFinalCanvas();
    if (!canvas) return;
    canvas.toBlob((blob) => {
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `qr-code-${Date.now()}.png`;
      a.click();
      URL.revokeObjectURL(url);
    }, "image/png");
  }, [getFinalCanvas]);

  const downloadSVG = useCallback(async () => {
    if (!text.trim()) return;
    if (plan === "free") {
      setGate("svg");
      return;
    }
    try {
      const svgString = await QRCode.toString(text, {
        type: "svg",
        width: size,
        margin: 2,
        color: { dark: fg, light: bg },
        errorCorrectionLevel: ecLevel,
      });
      const blob = new Blob([svgString], { type: "image/svg+xml" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `qr-code-${Date.now()}.svg`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      // fallback
    }
  }, [text, size, fg, bg, ecLevel, plan]);

  return (
    <ToolLayout
      name={tool.name}
      description={tool.description}
      longDescription={tool.longDescription}
      category={tool.category}
      categorySlug={tool.categorySlug}
      breadcrumbs={tool.breadcrumbs}
      icon={tool.icon}
      faq={FAQ}
      article={ARTICLE}
      relatedTools={relatedTools}
    >
      <div className="space-y-6">
        <div>
          <label className="mb-2 flex items-center gap-2 text-sm font-medium text-neutral-700 dark:text-neutral-300">
            <QrCode className="h-4 w-4" /> {t.qrCode.content}
          </label>
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder={t.qrCode.enterContent}
            rows={3}
            className="w-full rounded-lg border border-neutral-300 bg-white px-4 py-3 text-neutral-900 placeholder-neutral-400 focus:border-brand-500 focus:outline-none focus:ring-2 focus:ring-brand-500 dark:border-neutral-600 dark:bg-neutral-800 dark:text-white dark:placeholder-neutral-500"
          />
          <span className="mt-1 block text-right text-xs text-neutral-400">{t.qrCode.chars.replace("{count}", String(text.length))}</span>
        </div>

        <div className="grid gap-6 sm:grid-cols-2">
          <div className="space-y-6">
            <div>
              <label className="mb-2 block text-sm font-medium text-neutral-700 dark:text-neutral-300">{t.qrCode.errorCorrection}</label>
              <div className="grid grid-cols-2 gap-2">
                {(["L", "M", "Q", "H"] as const).map((level) => (
                  <button
                    key={level}
                    onClick={() => setEcLevel(level)}
                    className={`rounded-lg border-2 p-2 text-left transition-all ${
                      ecLevel === level
                        ? "border-brand-500 bg-brand-50 dark:bg-brand-900/20"
                        : "border-neutral-200 bg-white hover:border-neutral-300 dark:border-neutral-700 dark:bg-neutral-800"
                    }`}
                  >
                    <div className={`text-sm font-bold ${ecLevel === level ? "text-brand-600 dark:text-brand-400" : "text-neutral-900 dark:text-white"}`}>{level}</div>
                    <div className="text-xs text-neutral-500">
                      {level === "L" ? "7%" : level === "M" ? "15%" : level === "Q" ? "25%" : "30%"}
                    </div>
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="mb-2 flex items-center gap-2 text-sm font-medium text-neutral-700 dark:text-neutral-300">
                <Palette className="h-4 w-4" /> {t.qrCode.colors}
              </label>
              <div className="mb-3 grid grid-cols-2 gap-3">
                <div>
                  <label className="mb-1 block text-xs text-neutral-500">{t.qrCode.foreground}</label>
                  <div className="flex gap-2">
                    <input type="color" value={fg} onChange={(e) => setFg(e.target.value)}
                      className="h-8 w-8 cursor-pointer rounded border border-neutral-300 p-0.5 dark:border-neutral-600" />
                    <input type="text" value={fg} onChange={(e) => setFg(e.target.value)}
                      className="min-w-0 flex-1 rounded-lg border border-neutral-300 px-2 py-1 font-mono text-xs dark:border-neutral-600 dark:bg-neutral-800 dark:text-white" />
                  </div>
                </div>
                <div>
                  <label className="mb-1 block text-xs text-neutral-500">{t.qrCode.background}</label>
                  <div className="flex gap-2">
                    <input type="color" value={bg} onChange={(e) => setBg(e.target.value)}
                      className="h-8 w-8 cursor-pointer rounded border border-neutral-300 p-0.5 dark:border-neutral-600" />
                    <input type="text" value={bg} onChange={(e) => setBg(e.target.value)}
                      className="min-w-0 flex-1 rounded-lg border border-neutral-300 px-2 py-1 font-mono text-xs dark:border-neutral-600 dark:bg-neutral-800 dark:text-white" />
                  </div>
                </div>
              </div>
              <div className="flex flex-wrap gap-1.5">
                {PRESETS.map((p) => (
                  <button
                    key={p.name}
                    title={presetLabels[p.name] ?? p.name}
                    onClick={() => { setFg(p.fg); setBg(p.bg); }}
                    className="h-7 w-7 rounded-md border-2 border-neutral-300 dark:border-neutral-600"
                    style={{ background: `linear-gradient(135deg, ${p.fg} 50%, ${p.bg} 50%)` }}
                  />
                ))}
              </div>
            </div>

            <div>
              <label className="mb-2 flex items-center gap-2 text-sm font-medium text-neutral-700 dark:text-neutral-300">
                <Image className="h-4 w-4" /> {t.qrCode.logoOptional}
              </label>
              <div className="flex items-center gap-3">
                <button
                  onClick={() => fileInputRef.current?.click()}
                  className="rounded-lg border border-neutral-300 bg-white px-4 py-2 text-sm font-medium text-neutral-700 hover:bg-neutral-50 dark:border-neutral-600 dark:bg-neutral-800 dark:text-neutral-300"
                >
                  {logoDataUrl ? t.qrCode.changeLogo : t.qrCode.uploadLogo}
                </button>
                {logoDataUrl && (
                  <button onClick={() => setLogoDataUrl(null)} className="text-sm text-red-500 hover:underline">{t.common.remove}</button>
                )}
                <input ref={fileInputRef} type="file" accept="image/*" onChange={handleLogoUpload} className="hidden" />
              </div>
            </div>

            <div>
              <label className="mb-2 flex items-center gap-2 text-sm font-medium text-neutral-700 dark:text-neutral-300">
                <ZoomIn className="h-4 w-4" /> {t.qrCode.sizeLabel.replace("{size}", String(size))}
              </label>
              <input type="range" min={100} max={maxSize} step={50} value={size}
                onChange={(e) => setSize(Math.min(Number(e.target.value), maxSize))} className="w-full" />
              {plan === "free" && (
                <div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-neutral-500 dark:text-neutral-400">
                  <span>{t.qrCode.freeSizeLimit.replace("{size}", String(maxSize))}</span>
                  <ProBadge />
                </div>
              )}
            </div>
          </div>

          <div className="space-y-4">
            <div className="rounded-lg border border-neutral-200 bg-neutral-50 p-4 dark:border-neutral-700 dark:bg-neutral-800">
              <h3 className="mb-3 flex items-center gap-2 text-sm font-medium text-neutral-700 dark:text-neutral-300">
                <QrCode className="h-4 w-4" /> {t.qrCode.preview}
              </h3>
              {error ? (
                <div className="rounded-lg bg-red-50 p-4 text-center text-sm text-red-500">{error}</div>
              ) : qrDataUrl ? (
                <div className="flex items-center justify-center rounded-lg bg-neutral-100 p-4 dark:bg-neutral-900">
                  <canvas ref={canvasRef} className="hidden" />
                  {logoDataUrl ? (
                    <LogoPreview qrDataUrl={qrDataUrl} logoDataUrl={logoDataUrl} size={size} bg={bg} />
                  ) : (
                    <img src={qrDataUrl} alt={t.qrCode.qrAlt} style={{ maxWidth: "100%", maxHeight: size }} />
                  )}
                </div>
              ) : (
                <div className="flex items-center justify-center rounded-lg bg-neutral-100 p-8 dark:bg-neutral-900">
                  <div className="text-center text-neutral-400">
                    <QrCode className="mx-auto mb-2 h-8 w-8" />
                    <p className="text-sm">{t.qrCode.enterToGenerate}</p>
                  </div>
                </div>
              )}
            </div>

            <div className="flex gap-3">
              <button onClick={downloadPNG} disabled={!qrDataUrl}
                className="flex-1 rounded-lg bg-brand-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-700 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 disabled:opacity-50 flex items-center justify-center gap-2">
                <Download className="h-4 w-4" /> PNG
              </button>
              <button onClick={downloadSVG} disabled={!qrDataUrl}
                className="flex-1 rounded-lg bg-green-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 disabled:opacity-50 flex items-center justify-center gap-2">
                <Download className="h-4 w-4" /> SVG
              </button>
            </div>

            {plan === "free" && gate === "svg" && (
              <UpgradeGate description={t.qrCode.svgPro} />
            )}
          </div>
        </div>
      </div>
    </ToolLayout>
  );
}

function LogoPreview({ qrDataUrl, logoDataUrl, size, bg }: { qrDataUrl: string; logoDataUrl: string; size: number; bg: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    canvas.width = size;
    canvas.height = size;
    const img = new window.Image();
    img.onload = () => {
      ctx.drawImage(img, 0, 0, size, size);
      const logoSize = size * 0.25;
      const logoX = (size - logoSize) / 2;
      const logoY = (size - logoSize) / 2;
      const logoImg = new window.Image();
      logoImg.onload = () => {
        ctx.fillStyle = bg;
        ctx.beginPath();
        ctx.arc(size / 2, size / 2, logoSize / 2 + 3, 0, Math.PI * 2);
        ctx.fill();
        ctx.save();
        ctx.beginPath();
        ctx.arc(size / 2, size / 2, logoSize / 2, 0, Math.PI * 2);
        ctx.clip();
        ctx.drawImage(logoImg, logoX, logoY, logoSize, logoSize);
        ctx.restore();
      };
      logoImg.src = logoDataUrl;
    };
    img.src = qrDataUrl;
  }, [qrDataUrl, logoDataUrl, size, bg]);
  return <canvas ref={canvasRef} style={{ maxWidth: "100%", maxHeight: size }} />;
}
