// Types
export type {
  Tool,
  ToolAuthor,
  ToolVersion,
  ToolSEO,
  ToolStatus,
  ToolPermission,
  ToolInput,
  ToolOutput,
  InputType,
  Category,
  Tag,
  SearchResult,
  ToolFilter,
} from "./types";

// Constants
export { DEFAULT_CATEGORIES, SEARCH_CONFIG, TOOL_DEFAULTS, PAGINATION } from "./constants";

// Defaults
export {
  TOOL_VERSION_DEFAULTS,
  TOOL_SEO_DEFAULTS,
  TOOL_AUTHOR_DEFAULTS,
  TOOL_STATUS_DEFAULTS,
  TOOL_PERMISSIONS_DEFAULTS,
  TOOL_INPUT_DEFAULTS,
  TOOL_OUTPUT_DEFAULTS,
  TOOL_FIELD_DEFAULTS,
} from "./defaults";

// Utils
export { slugify, generateId, sortTools, searchTools } from "./utils";

// Validators
export { validateTool, isValidTool } from "./validators";
export type { ValidationError as ValidatorError } from "./validators";

// Parser
export { parseToolDefinition, parseToolDefinitions } from "./parser";
export type { ToolDefinition, ToolDefinitionInput, ToolDefinitionOutput } from "./parser";

// Registry
export { ToolRegistry, toolRegistry, CategoryRegistry, categoryRegistry } from "./registry";

// Loader
export { ToolLoader, toolLoader } from "./loader";

// Services
export { SearchRegistry, searchRegistry } from "./services";

// Plugin System
export {
  PluginManager,
  pluginManager,
  PluginRegistry,
  pluginRegistry,
  PluginLoader,
  pluginLoader,
  PluginValidator,
  pluginValidator,
} from "./plugin";

export type {
  Plugin,
  PluginManifest,
  PluginSchema,
  PluginSEO,
  PluginIcon,
  PluginPermissions,
  PluginContext,
  PluginResult,
  PluginManagerConfig,
  PluginValidationError,
} from "./plugin";

export {
  PluginNotFoundError,
  PluginDuplicateError,
  PluginInvalidError,
  PluginExecutionError,
} from "./plugin";

export type { PluginError as PluginBaseError } from "./plugin";

// Search Engine
export {
  SearchService,
  searchService,
  SearchIndex,
  searchIndex,
  RankingSystem,
  rankingSystem,
  SuggestionEngine,
  suggestionEngine,
  SearchHistory,
  searchHistory,
} from "./search";

export type {
  SearchConfig,
  SearchResult as SearchServiceResult,
  SearchResponse,
  IndexEntry,
  SearchIndexConfig,
  RankConfig,
  RankedResult,
  Suggestion,
  SuggestionConfig,
  SearchRecord,
  SearchHistoryConfig,
} from "./search";

// SEO Engine
export {
  SEOService,
  seoService,
  MetaGenerator,
  metaGenerator,
  OpenGraphGenerator,
  openGraphGenerator,
  TwitterGenerator,
  twitterGenerator,
  SitemapGenerator,
  sitemapGenerator,
  BreadcrumbGenerator,
  breadcrumbGenerator,
  createWebApplicationSchema,
  createSoftwareApplicationSchema,
  createArticleSchema,
  createBreadcrumbSchema,
  createCollectionPageSchema,
  createFAQSchema,
  createOrganizationSchema,
  createWebsiteSchema,
} from "./seo";

export type {
  SEOConfig,
  MetaTags,
  OpenGraph,
  TwitterCard,
  JsonLdSchema,
  BreadcrumbItem,
  SitemapEntry,
  SEOOutput,
  ToolSEOInput,
  CategorySEOInput,
  ArticleSEOInput,
} from "./seo";

// Analytics Core
export {
  AnalyticsService,
  analyticsService,
  EventStore,
  eventStore,
  AnalyticsProcessor,
  createProcessor,
  createToolViewEvent,
  createToolUsageEvent,
  createToolErrorEvent,
  createConversionEvent,
  createDownloadEvent,
  createSearchQueryEvent,
  createPageViewEvent,
  createSessionStartEvent,
  createSessionEndEvent,
} from "./analytics";

export type {
  EventType,
  AnalyticsEvent,
  EventMetadata,
  ToolViewEvent,
  ToolUsageEvent,
  ToolErrorEvent,
  ConversionEvent,
  DownloadEvent,
  SearchQueryEvent,
  AnalyticsSummary,
  ToolAnalytics,
  PopularTool,
  ActivityEntry,
  TimeSeriesPoint,
  AnalyticsConfig,
} from "./analytics";

// Error Framework
export {
  ToolNovaError,
  ValidationError,
  PluginError,
  ApiError,
  UnknownError,
  RecoveryManager,
  recoveryManager,
  ToolNovaErrorHandler,
  errorHandler,
  Logger,
  logger,
  ERROR_CODES,
  getErrorCode,
  findErrorCode,
} from "./errors";

export type {
  ErrorContext,
  ErrorSeverity,
  ErrorCategory,
  SerializedError,
  ErrorHandler,
  RecoveryStrategy,
  ErrorCodeGroup,
  ErrorCodeEntry,
  RetryConfig,
  LogLevel,
  LogEntry,
  LoggerConfig,
} from "./errors";

// Auth Foundation
export {
  ROLE_PERMISSIONS,
  TokenService,
  tokenService,
  AuthService,
  authService,
  SessionManager,
  sessionManager,
  AuthGuard,
  authGuard,
  localStrategy,
  LocalStrategy,
} from "./auth";

export type {
  UserRole,
  Permission,
  User,
  Session,
  AuthTokens,
  LoginCredentials,
  RegisterData,
  PasswordResetRequest,
  PasswordResetConfirm,
  EmailVerification,
  AuthState,
  TokenConfig,
  AuthConfig,
  AuthGuardResult,
  AuthStrategy,
} from "./auth";

// Tool SDK
export {
  BaseTool,
  ToolContextImpl,
  createToolContext,
  ToolLogger,
  createToolLogger,
  ToolValidator,
  toolValidator,
  validateToolInputs,
  TOOL_LOG_LEVELS,
  DEFAULT_TOOL_CONFIG,
  DEFAULT_TOOL_PERMISSIONS,
  defineInput,
  defineInputs,
  defineOutput,
  defineOutputs,
  formatOutputValue,
  createSuccessResult,
  createErrorResult,
  addWarning,
  createPermissions,
  hasCapability,
  checkAccess,
  createExecution,
  transitionPhase,
  updateProgress,
  setExecutionError,
  generateExecutionId,
  slugifyToolName,
} from "./sdk";

export type {
  BaseToolOptions,
  ToolContextOptions,
  ToolValidationResult,
  ToolValidationError,
  ToolValidationWarning,
  ToolLogLevel,
  ToolLogEntry,
  ToolLoggerConfig,
  ToolConfig,
  ToolConfigPermission,
  ToolRateLimit,
  ToolConfigMetadata,
  ToolConfigOverrides,
  ToolMetadata,
  ToolMetadataAuthor,
  ToolMetadataInput,
  ToolMetadataOutput,
  ToolInputDefinition,
  ToolInputType,
  ToolInputValidator,
  ToolInputResult,
  ToolOutputDefinition,
  ToolOutputType,
  ToolOutputFormatted,
  ToolResult,
  ToolResultError,
  ToolResultWarning,
  ToolResultMetadata,
  ToolOutputResult,
  ToolPermissions,
  ToolAccessLevel,
  ToolCapability,
  ToolAccessCheckResult,
  ToolExecutionPhase,
  ToolExecution,
  ToolExecutionStatus,
  ToolProgress,
  ToolExecutionError,
  ToolExecutionMetadata,
  ToolExecutionTimer,
  ToolContext,
} from "./sdk";

// Image Processing Engine
export {
  ImageEngine,
  ImageOperations,
  ImageMetadataReader,
  ImagePipeline,
  BaseImageAdapter,
  IMAGE_FORMATS,
  IMAGE_FORMAT_MIME,
  SUPPORTED_FORMATS,
  DEFAULT_ENGINE_CONFIG,
  createColor,
  COLORS,
  isValidFormat,
  normalizeFormat,
  resolveColor,
} from "./engine";

export type {
  ImageEngineOptions as ImageEngineConstructorOptions,
  ImageFormat,
  ImageColorSpace,
  ImageInterpolation,
  ImageFlipDirection,
  ImageBlendMode,
  ImageExtendBackground,
  ImageOutputFormat,
  ImageMetadata,
  ImageExifData,
  ImageGPSData,
  ImageICCProfile,
  ImageDimension,
  ImageRegion,
  ImagePoint,
  ImagePadding,
  ImageColor,
  ImageOperationType,
  ImageOperation,
  ResizeParams,
  CompressParams,
  RotateParams,
  CropParams,
  MergeParams,
  MergeOperation,
  SplitParams,
  ConvertParams,
  FlipParams,
  TrimParams,
  ExtendParams,
  FlattenParams,
  NegateParams,
  NormalizeParams,
  BlurParams,
  SharpenParams,
  ThresholdParams,
  ModulateParams,
  TintParams,
  GammaParams,
  ImageOperationParams,
  ImageEngineConfig,
  ImageEngineOptions,
  ImageLoadOptions,
  ImageSaveOptions,
  ImageInfo,
  ImageProcessResult,
  ImageBatchItem,
  ImageOperationConfig,
  ImageAdapter,
  ImageHandle,
  ImageSummary,
  ImagePipelineResult,
} from "./engine";

// File Storage Engine
export {
  FileStorage,
  StorageValidator,
  TempFileManager,
  FileSystemAdapter,
  generateFileId,
  generateTempFileId,
  generateUniqueFilename,
  getExtension,
  sanitizeFilename,
  normalizePath,
  joinPath,
  getDirectoryFromPath,
  isPathSecure,
  hasPathTraversal,
  formatFileSize,
  parseFileSize,
  computeHash,
  computeFileHash,
  computeStreamHash,
  verifyHash,
  computeHashes,
  createChecksum,
  verifyChecksum,
  hashToFilename,
  generateIntegrityToken,
  FILE_STATUS,
  COMMON_MIME_TYPES,
  EXTENSION_MIME_MAP,
  DEFAULT_STORAGE_CONFIG,
} from "./storage";

export type {
  StorageBackend,
  FileStatus,
  HashAlgorithm,
  StoredFile,
  FileMetadata,
  FileReference,
  StorageConfig,
  StorageOptions,
  UploadOptions,
  StorageQuota,
  StorageStats,
  ValidationRule,
  ValidationRuleType,
  ValidationResult,
  ValidationError as StorageValidationError,
  ValidationWarning,
  FileValidationInput,
  MimeValidationResult,
  HashValidationResult,
  StorageAdapter,
  StorageWriteOptions,
  StorageWriteResult,
  StorageFileInfo,
  TempFileEntry,
  FileStorageEvent,
  FileStorageListener,
} from "./storage";

// Tool Marketplace
export {
  Marketplace,
  marketplace,
  SecurityScanner,
  securityScanner,
  CompatibilityChecker,
  compatibilityChecker,
  ApprovalWorkflow,
  approvalWorkflow,
  VersionManager,
  versionManager,
  SubmissionService,
  submissionService,
  MarketplaceStore,
  marketplaceStore,
} from "./marketplace";

export type {
  PluginSubmissionStatus,
  PluginReviewStatus,
  PluginReviewType,
  SeverityLevel,
  ReleaseChannel,
  CompatibilityStatus,
  PluginSubmission,
  PluginReview,
  ReviewComment,
  ReviewChecklistItem,
  PluginVersion,
  PluginDependency,
  BreakingChange,
  VersionAsset,
  VersionMetadata,
  SecurityScan,
  SecurityScanResult,
  SecurityVulnerability,
  MalwareIndicator,
  CodeAnalysisResult,
  CodeIssue,
  PermissionAuditResult,
  PluginRequiredPermission,
  DependencyAuditResult,
  DependencyRisk,
  LicenseComplianceResult,
  LicenseViolation,
  CompatibilityCheck,
  CompatibilityResult,
  PlatformCompatibility,
  RuntimeCompatibility,
  DependencyCompatibility,
  ApiCompatibility,
  CompatibilityWarning,
  MarketplacePlugin,
  PluginAuthor,
  PluginStats,
  MarketplaceMetadata,
  MarketplaceEvent,
  MarketplaceEventType,
  MarketplaceConfig,
  SubmissionConfig,
  ReviewConfig,
  SecurityConfig,
  VersioningConfig,
  CompatibilityConfig,
  StoreQuery,
  StoreResult,
  ReviewDecision,
  VersionBumpResult,
  SubmissionResult,
  PluginRegistrationInput,
  MarketplaceStats,
} from "./marketplace";

// QR Code Generator
export {
  encode as qrEncode,
  renderSVG as qrRenderSVG,
  svgToDataUrl as qrSvgToDataUrl,
  downloadFile as qrDownloadFile,
  copyImageToClipboard as qrCopyToClipboard,
  getDownloadHistory as qrGetDownloadHistory,
  addToHistory as qrAddToHistory,
  removeFromHistory as qrRemoveFromHistory,
  clearHistory as qrClearHistory,
  formatTimestamp as qrFormatTimestamp,
  createQRCodeGeneratorConfig,
  createDefaultQRConfig,
  EC_LEVELS as QR_EC_LEVELS,
  DEFAULT_QR_CONFIG,
  MAX_VERSION as QR_MAX_VERSION,
  getDataCapacity as qrGetDataCapacity,
  getECCount as qrGetECCount,
  getBlockInfo as qrGetBlockInfo,
  getTotalCodewords as qrGetTotalCodewords,
} from "./tools/qr-code-generator";

export type {
  ECLevel as QRECLevel,
  QRConfig,
  QRMatrix,
  QRModule,
  EncodingMode,
  RenderOptions,
  DownloadHistoryEntry,
  QRCodeGeneratorInput,
  QRCodeGeneratorOutput,
} from "./tools/qr-code-generator";

// Image Compressor
export {
  extractExifFromJpeg,
  buildExifBuffer,
  stripExif,
  copyExifToOutput,
  validateImageFile,
  getImageDimensionsFromBuffer,
  loadImageFromFile,
  compressImage,
  formatFileSize as formatFileSizeCompat,
  getSavingsColor,
  compressBatch,
  compressSingle,
  downloadCompressedImage,
  downloadAllCompressed,
  downloadAsZip,
  createImageCompressorConfig,
  createDefaultCompressionConfig,
  COMPRESSION_PRESETS,
  FORMAT_QUALITY_RANGES,
  DEFAULT_COMPRESSION_CONFIG,
  MAX_FILE_SIZE,
  MAX_BATCH_SIZE,
  ALLOWED_TYPES,
  ALLOWED_EXTENSIONS,
} from "./tools/image-compressor";

export type {
  CompressionFormat,
  CompressionPreset,
  CompressionQuality,
  CompressionConfig,
  ResizeConfig,
  ImageFile,
  CompressedImage,
  CompressionResult,
  BatchCompressionResult,
  ExifData,
  ImageCompressorInput,
  ImageCompressorOutput,
} from "./tools/image-compressor";

// PDF Merger
export {
  parsePdf,
  getPageCount,
  getPageDimensions,
  mergePdfBuffers,
  getPageInfoFromParsed,
  loadPdfFromFile,
  validatePdfFile,
  getPageInfos,
  formatFileSize as formatFileSizePdf,
  downloadBlob,
  createPdfMergerConfig,
  createDefaultMergeConfig,
  DEFAULT_MERGE_CONFIG,
  MAX_PDF_SIZE,
  MAX_PDF_FILES,
  ALLOWED_PDF_TYPES,
  ALLOWED_PDF_EXTENSIONS,
} from "./tools/pdf-merger";

export type {
  PdfVersion,
  PdfInputFile,
  PdfPageInfo,
  PdfMergeConfig,
  PdfMergeResult,
  PdfParserError,
  PdfObjectRef,
  PdfXrefEntry,
  PdfXref,
  PdfTrailer,
  PdfParsedDocument,
  MergedPdfResult,
  PdfMergerInput,
  PdfMergerOutput,
} from "./tools/pdf-merger";

// Resume Builder
export {
  renderResumeHtml,
  getOrderedVisibleSections,
  formatDate,
  formatDateRange,
  escapeHtml,
  nlToBr,
  getSectionLabel,
  getSkillLevelLabel,
  getProficiencyLabel,
  renderClassic,
  renderModern,
  renderMinimal,
  exportResumeToPdf,
  renderForPreview,
  createEmptyResume,
  saveDraft,
  getAllDrafts,
  getDraft,
  deleteDraft,
  duplicateDraft,
  exportDraftAsJson,
  importDraftFromJson,
  createResumeBuilderConfig,
  createDefaultResumeData,
  SKILL_LEVELS,
  LANGUAGE_PROFICIENCIES,
  SECTION_LABELS,
  RESUME_TEMPLATES,
  DEFAULT_PERSONAL_INFO,
  DEFAULT_SECTION_VISIBILITY,
  DEFAULT_SECTION_ORDER,
  SKILL_CATEGORIES,
  SKILL_CATEGORIES_AR,
} from "./tools/resume-builder";

export type {
  ResumeLanguage,
  ResumeDirection,
  TemplateStyle,
  SectionKey,
  PersonalInfo,
  EducationEntry,
  ExperienceEntry,
  SkillEntry,
  SkillLevel,
  LanguageEntry,
  LanguageProficiency,
  ProjectEntry,
  ReferenceEntry,
  ResumeSections,
  SectionVisibility,
  ResumeData,
  ResumeTemplate,
  ResumeDraft,
  ResumeExportOptions,
  PdfExportResult as ResumePdfExportResult,
  ResumeBuilderInput,
  ResumeBuilderOutput,
} from "./tools/resume-builder";
