import {
  AlignStartVertical,
  ArrowLeftRight,
  ArrowRightLeft,
  Binary,
  Braces,
  Cake,
  Calculator,
  CalendarDays,
  CaseSensitive,
  CaseUpper,
  Code,
  CodeXml,
  Coins,
  Crop,
  Dices,
  Diff,
  Droplets,
  FileArchive,
  FileBox,
  FileCode,
  FileImage,
  FileTerminal,
  FileText,
  FileType,
  FileUser,
  Files,
  Globe,
  Hash,
  HeartPulse,
  Hourglass,
  IdCard,
  Image,
  ImageDown,
  ImageUp,
  Key,
  KeyRound,
  Landmark,
  Link,
  Link2,
  List,
  Merge,
  MoveDiagonal,
  Palette,
  PanelsTopLeft,
  Percent,
  Pipette,
  QrCode,
  Regex,
  Repeat2,
  RefreshCw,
  Ruler,
  ShieldCheck,
  Shrink,
  Shuffle,
  Sigma,
  Sparkles,
  Split,
  SquareFunction,
  Star,
  Terminal,
  TextQuote,
  Thermometer,
  Timer,
  Type,
  Wallet,
  WandSparkles,
  type LucideIcon,
} from "lucide-react";

const WEB_ICON_MAP: Record<string, LucideIcon> = {
  "type": Type,
  "case-sensitive": CaseSensitive,
  "case-upper": CaseUpper,
  "list": List,
  "timer": Timer,
  "diff": Diff,
  "repeat-2": Repeat2,
  "arrow-left-right": ArrowLeftRight,
  "link": Link,
  "terminal": Terminal,
  "shield-check": ShieldCheck,
  "text-quote": TextQuote,
  "align-start-vertical": AlignStartVertical,
  "image": Image,
  "image-down": ImageDown,
  "image-up": ImageUp,
  "move-diagonal": MoveDiagonal,
  "shuffle": Shuffle,
  "crop": Crop,
  "pipette": Pipette,
  "binary": Binary,
  "file-code": FileCode,
  "star": Star,
  "droplets": Droplets,
  "panels-top-left": PanelsTopLeft,
  "wand-sparkles": WandSparkles,
  "braces": Braces,
  "code-xml": CodeXml,
  "code": Code,
  "shrink": Shrink,
  "file-terminal": FileTerminal,
  "file-box": FileBox,
  "id-card": IdCard,
  "palette": Palette,
  "file-type": FileType,
  "hash": Hash,
  "key-round": KeyRound,
  "link-2": Link2,
  "regex": Regex,
  "qr-code": QrCode,
  "calculator": Calculator,
  "percent": Percent,
  "heart-pulse": HeartPulse,
  "wallet": Wallet,
  "landmark": Landmark,
  "cake": Cake,
  "calendar-days": CalendarDays,
  "hourglass": Hourglass,
  "square-function": SquareFunction,
  "ruler": Ruler,
  "coins": Coins,
  "thermometer": Thermometer,
  "files": Files,
  "globe": Globe,
  "sigma": Sigma,
  "refresh-cw": RefreshCw,
  "arrow-right-left": ArrowRightLeft,
  "key": Key,
  "dices": Dices,
  "sparkles": Sparkles,
  "merge": Merge,
  "file-archive": FileArchive,
  "file-image": FileImage,
  "split": Split,
  "file-user": FileUser,
  "file-text": FileText,
};

export function getDbIcon(name?: string | null): LucideIcon | undefined {
  if (!name) return undefined;
  const key = name.toLowerCase().replace(/[\s_]+/g, "-");
  return WEB_ICON_MAP[key] ?? WEB_ICON_MAP[name] ?? undefined;
}

export function DbIcon({ name, className }: { name?: string | null; className?: string }) {
  const Icon = name
    ? (WEB_ICON_MAP[name.toLowerCase().replace(/[\s_]+/g, "-")] ?? WEB_ICON_MAP[name])
    : undefined;
  if (!Icon) return null;
  return <Icon className={className} aria-hidden />;
}
